In [3]:
import pandas as pd
from sqlalchemy import create_engine

In [4]:
df = pd.read_csv('sales.csv')

# 1 Изучение данных

In [3]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   object
 1   Branch                   1000 non-null   object
 2   City                     1000 non-null   object
 3   Customer type            1000 non-null   object
 4   Gender                   1000 non-null   object
 5   Product line             1000 non-null   object
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Total                    1000 non-null   float64
 10  Date                     1000 non-null   object
 11  Time                     1000 non-null   object
 12  Payment                  1000 non-null   object
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: float64(7), int64(1), object(9)
memory usage: 132.9+ KB

Наименование столбцов на русском

* 0 Идентификатор счета
* 1 Филиал
* 2 Город
* 3 Тип клиента
* 4 Пол
* 5 Линейка товаров
* 6 Цена за единицу
* 7 Количество
* 8 Налог 5%
* 9 Итого
* 10 Дата
* 11 Время
* 12 Оплата
* 13 Себестоимость
* 14 брутто процент маржи
* 15 валовой доход
* 16 Рейтинг

In [5]:
df.describe()

,Unit price,Quantity,Tax 5%,Total,cogs,gross margin percentage,gross income,Rating
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1.000000e+03,1000.000000,1000.00000
mean,55.672130,5.510000,15.379369,322.966749,307.58738,4.761905e+00,15.379369,6.97270
std,26.494628,2.923431,11.708825,245.885335,234.17651,6.131498e-14,11.708825,1.71858
min,10.080000,1.000000,0.508500,10.678500,10.17000,4.761905e+00,0.508500,4.00000
25%,32.875000,3.000000,5.924875,124.422375,118.49750,4.761905e+00,5.924875,5.50000
50%,55.230000,5.000000,12.088000,253.848000,241.76000,4.761905e+00,12.088000,7.00000
75%,77.935000,8.000000,22.445250,471.350250,448.90500,4.761905e+00,22.445250,8.50000
max,99.960000,10.000000,49.650000,1042.650000,993.00000,4.761905e+00,49.650000,10.00000

In [6]:
len(df['Invoice ID'].unique())

1000

Invoice ID уникален во всем датасете, может быть использован как первичный ключ для таблицы продаж.

In [7]:
for i in df.columns.to_list():
    print(i, end = ' - количество уникальных значений ------------ ')
    print(len(df[i].unique()))

Invoice ID - количество уникальных значений ------------ 1000
Branch - количество уникальных значений ------------ 3
City - количество уникальных значений ------------ 3
Customer type - количество уникальных значений ------------ 2
Gender - количество уникальных значений ------------ 2
Product line - количество уникальных значений ------------ 6
Unit price - количество уникальных значений ------------ 943
Quantity - количество уникальных значений ------------ 10
Tax 5% - количество уникальных значений ------------ 990
Total - количество уникальных значений ------------ 990
Date - количество уникальных значений ------------ 89
Time - количество уникальных значений ------------ 506
Payment - количество уникальных значений ------------ 3
cogs - количество уникальных значений ------------ 990
gross margin percentage - количество уникальных значений ------------ 1
gross income - количество уникальных значений ------------ 990
Rating - количество уникальных значений ------------ 61

Столбцы со строковым типом данных и не большим количеством значений должны стать основой нормализации.

In [8]:
df[['Branch','City','Invoice ID']].groupby(['Branch','City'])['Invoice ID'].count()

Branch  City
A       Yangon       340
B       Mandalay     332
C       Naypyitaw    328
Name: Invoice ID, dtype: int64

Филиал и город взаимосвязаны, можно их поместить в одну таблицу-справочник.

In [9]:
df['Customer type'].unique()

array(['Member', 'Normal'], dtype=object)

In [10]:
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [11]:
df['Product line'].unique()

array(['Health and beauty', 'Electronic accessories',
       'Home and lifestyle', 'Sports and travel', 'Food and beverages',
       'Fashion accessories'], dtype=object)

In [12]:
df['Payment'].unique()

array(['Ewallet', 'Cash', 'Credit card'], dtype=object)

Для слоя NDS будут созданы следующие таблицы:

* Уникальные города и филиалы → nds.locations

* Уникальные типы клиентов → nds.customer_types

* Уникальные линейки продуктов → nds.products

* Уникальные способы оплаты → nds.payment_types

* Таблица фактов продажи → nds.sales

# 2 создание таблиц слоя NDS и DDS в postgresql

DDL скрипты создания таблиц запускаются в postgresql

In [1]:
pip install psycopg2

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2 in c:\users\79136\appdata\roaming\python\python311\site-packages (2.9.12)
Note: you may need to restart the kernel to use updated packages.

Подключение к postgresql и заполнение таблиц-справочников

In [5]:
engine = create_engine('postgresql://python_user:python_pass@localhost:5432/final_work_de')

In [6]:
#функция для загрузки данных на слой NDS, нормализованный факт и справочники
def load_nds(df, engine):
    
    locations = df[['Branch', 'City']].rename(columns={'Branch': 'branch','City': 'city'}).drop_duplicates()
    locations.to_sql('locations', engine, schema='nds', if_exists='append', index=False)
    
    customer_types = df[['Customer type']].rename(columns={'Customer type': 'customer_type_name'}).drop_duplicates()
    customer_types.to_sql('customer_types', engine, schema='nds', if_exists='append', index=False)

    genders = df[['Gender']].rename(columns={'Gender': 'gender_name'}).drop_duplicates()
    genders.to_sql('genders', engine, schema='nds', if_exists='append', index=False)
    
    product_lines = df[['Product line']].rename(columns={'Product line': 'product_line_name'}).drop_duplicates()
    product_lines.to_sql('product_lines', engine, schema='nds', if_exists='append', index=False)
    
    payment_types = df[['Payment']].rename(columns={'Payment': 'payment_method'}).drop_duplicates()
    payment_types.to_sql('payment_types', engine, schema='nds', if_exists='append', index=False)
    
    # маппинги для внешних ключей для join
    locations_map = pd.read_sql("SELECT location_id, branch, city FROM nds.locations", engine)
    customer_types_map = pd.read_sql("SELECT customer_type_id, customer_type_name FROM nds.customer_types", engine)
    genders_map = pd.read_sql("SELECT gender_id, gender_name FROM nds.genders", engine)
    product_lines_map = pd.read_sql("SELECT product_line_id, product_line_name FROM nds.product_lines", engine)
    payment_types_map = pd.read_sql("SELECT payment_type_id, payment_method FROM nds.payment_types", engine)
    
    # Преобразуем DataFrame фактов
    facts = df.copy()
    
    # Маппинг названий в ID через join
    facts = facts.merge(locations_map, left_on=['Branch', 'City'], right_on=['branch', 'city'], how='left')
    facts = facts.merge(customer_types_map, left_on=['Customer type'], right_on=['customer_type_name'], how='left')
    facts = facts.merge(genders_map, left_on=['Gender'], right_on=['gender_name'], how='left')
    facts = facts.merge(product_lines_map, left_on=['Product line'], right_on=['product_line_name'], how='left')
    facts = facts.merge(payment_types_map, left_on=['Payment'], right_on=['payment_method'], how='left')
    
    # Преобразование даты и времени в формат БД из текста
    facts['Date'] = pd.to_datetime(facts['Date'])
    facts['Time'] = pd.to_datetime(facts['Time'], format='%H:%M').dt.time
    
    # Выбор нужных колонок для nds.sales
    facts_nds = facts[[
        'Invoice ID', 'location_id', 'customer_type_id', 'gender_id', 
        'product_line_id', 'payment_type_id', 'Unit price', 'Quantity', 
        'Tax 5%', 'Total', 'cogs', 'gross margin percentage', 'gross income',
        'Rating', 'Date', 'Time'
    ]].copy()
    
    # Переименовывание колонок в соответствии с названием в БД
    facts_nds.columns = [
        'invoice_id', 'location_id', 'customer_type_id', 'gender_id',
        'product_line_id', 'payment_type_id', 'unit_price', 'quantity',
        'tax_5_percent', 'total', 'cogs', 'gross_margin_percent', 'gross_income',
        'rating', 'sale_date', 'sale_time'
    ]
    
    # Загрузка в БД
    facts_nds.to_sql('sales', engine, schema='nds', if_exists='append', index=False)
    
    return len(facts_nds)

In [9]:
# Запуск функции для загрузки факта в БД на слой nds
load_nds(df, engine)

1000

# 3 заполнение таблицы на слое DDS

Запуск скрипта для заполнения таблицы выполним из файла nds_to_dds.sql

In [10]:
# Открытие файла и чтение его содержимого
with open("nds_to_dds.sql") as file:
    sql_query = file.read()

# Подключение к базе данных и выполнение запроса
with engine.connect() as con:
    con.execute(sql_query)

# 4 запуск проверок и заполнение таблицы с результатами nds.dq_result

In [33]:
import psycopg2
from sqlalchemy import create_engine, text

In [36]:
# Параметры подключения из engine
db_url = str(engine.url)

# Подключаемся через psycopg2
conn = psycopg2.connect(db_url)
conn.autocommit = True

try:
    with open("data_quality_check.sql") as file:
        sql_content = file.read()
    
    with conn.cursor() as cur:
        cur.execute(sql_content)
        print("Данные успешно вставлены")
    
except Exception as e:
    print(f"Ошибка: {e}")
    conn.rollback()
finally:
    conn.close()

Данные успешно вставлены